// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwO4UKv_JXWsz31Xx8Z_NBIXFIf6JFxAA',
    appId: '1:140471539326:web:f821bbd80198356e026a2f',
    messagingSenderId: '140471539326',
    projectId: 'todo-729b6',
    authDomain: 'todo-729b6.firebaseapp.com',
    databaseURL: 'https://todo-729b6-default-rtdb.firebaseio.com',
    storageBucket: 'todo-729b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApN7tAfFYs9c6_V4LavOXZNMAVLhjLHR0',
    appId: '1:140471539326:android:0f72a206114a339b026a2f',
    messagingSenderId: '140471539326',
    projectId: 'todo-729b6',
    databaseURL: 'https://todo-729b6-default-rtdb.firebaseio.com',
    storageBucket: 'todo-729b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx529aUBcHrWmNGJAZBqSApxg5F9BY_go',
    appId: '1:140471539326:ios:99683ab7a0031512026a2f',
    messagingSenderId: '140471539326',
    projectId: 'todo-729b6',
    databaseURL: 'https://todo-729b6-default-rtdb.firebaseio.com',
    storageBucket: 'todo-729b6.appspot.com',
    iosBundleId: 'com.example.riverpodFlutterTotoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx529aUBcHrWmNGJAZBqSApxg5F9BY_go',
    appId: '1:140471539326:ios:99683ab7a0031512026a2f',
    messagingSenderId: '140471539326',
    projectId: 'todo-729b6',
    databaseURL: 'https://todo-729b6-default-rtdb.firebaseio.com',
    storageBucket: 'todo-729b6.appspot.com',
    iosBundleId: 'com.example.riverpodFlutterTotoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwO4UKv_JXWsz31Xx8Z_NBIXFIf6JFxAA',
    appId: '1:140471539326:web:afa22969542aff03026a2f',
    messagingSenderId: '140471539326',
    projectId: 'todo-729b6',
    authDomain: 'todo-729b6.firebaseapp.com',
    databaseURL: 'https://todo-729b6-default-rtdb.firebaseio.com',
    storageBucket: 'todo-729b6.appspot.com',
  );
}
